academy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), # /admin/
    path('', include('home.urls')), # /
    path('flashcards/', include('flashcard.urls')), # /flashcards/
    path('mathbubbles/', include('mathbubbles.urls')), # /mathbubbles/
    path('quizzes/', include('quizzes.urls')), # /quizzes/
    path('typer/', include('typer.urls')), # /typer/
]

home/urls.py
from django.shortcuts import render
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home')
]

quizzes/urls.py
from django.urls import path

from . import views

app_name = 'quizzes'

urlpatterns = [
    # base route shows the list of quizzes
    path('', views.QuizListView.as_view(), name='quiz-list'),
    # route for taking a quiz
    path('quiz/<str:id>/take', views.take_quiz, name='take_quiz'),
    # route for submitting a quiz
    path('quiz/<str:id>/submit_attempt', views.submit_quiz_attempt, name='submit_quiz_attempt'),
    # route for showing the results of a quiz
    path('results/<str:id>', views.quiz_results, name='quiz_results'),
]

quizzes/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models

# This model will store the name of the quiz
class Quiz(models.Model):
    id = models.UUIDField(primary_key = True,
         default = uuid.uuid4,
         editable = False)

    name = models.CharField(max_length=64, blank=False, null=False, default="")

    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    timestamp = models.DateTimeField(auto_now_add=True, db_index=True, editable=False)

    class Meta:
        verbose_name_plural = "Quizzes"
    
    def __str__(self):
        return self.name


# This model will store a question that belongs to a quiz
class Question(models.Model):
    id = models.UUIDField(primary_key = True,
         default = uuid.uuid4,
         editable = False)

    quiz = models.ForeignKey(Quiz, blank=False, null=False, on_delete=models.CASCADE)

    title = models.CharField(max_length=256, blank=False, null=False, default="")

    def __str__(self):
        return "Quiz: " + str(self.quiz) + " Question: " + self.title


# This model will store the options for answers that belong to a question
class QuestionOption(models.Model):
    id = models.UUIDField(primary_key = True,
         default = uuid.uuid4,
         editable = False)

    question = models.ForeignKey(Question, blank=False, null=False, on_delete=models.CASCADE)

    title = models.CharField(max_length=256, blank=False, null=False, default="")

    ordering = models.CharField(max_length=8, blank=False, null=False, default="3")

    correct = models.BooleanField(default=False)

    def __str__(self):
        return 'Answer for ' + str(self.question) + ': ' + self.title


# This model will store the user's attempt to respond to a quiz
class QuizAttempt(models.Model):
    id = models.UUIDField(primary_key = True,
         default = uuid.uuid4,
         editable = False)

    quiz = models.ForeignKey(Quiz, blank=False, null=False, on_delete=models.CASCADE)

    completed_by = models.ForeignKey(User, on_delete=models.CASCADE)

    timestamp = models.DateTimeField(auto_now_add=True, db_index=True, editable=False)

    def __str__(self):
        return str(self.quiz) + ' completed by ' + str(self.completed_by) + ' at ' + str(self.timestamp)


# This model will store the user's response to a question on a quiz as part of an attempt
class QuestionAttempt(models.Model):
    id = models.UUIDField(primary_key = True,
         default = uuid.uuid4,
         editable = False)

    attempt = models.ForeignKey(QuizAttempt, blank=False, null=False, on_delete=models.CASCADE)

    question = models.ForeignKey(Question, blank=False, null=False, on_delete=models.CASCADE)

    user_response = models.ForeignKey(QuestionOption, blank=False, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.attempt.completed_by) + ' answered ' + str(self.user_response) + ' on ' + str(self.question)

quizzes/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import get_template
from django.utils import timezone
from django.views.generic.list import ListView

from .models import Quiz, QuizAttempt, QuestionAttempt, QuestionOption

# This will list all of the quizzes that have been created
class QuizListView(ListView):
    model = Quiz

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    
# This will show the questions of a quiz and allow the user to answer them
def take_quiz(request, id):
    quiz = get_object_or_404(Quiz, id=id)

    template = get_template("quizzes/take_quiz.html")
    return HttpResponse(template.render({"quiz": quiz}, request))

# This will record the user's answers to the quiz
def submit_quiz_attempt(request, id): 
    quiz = get_object_or_404(Quiz, id=id)

    attempt = QuizAttempt.objects.create(quiz=quiz, completed_by=request.user)

    for question in quiz.question_set.all():
        selected_option = QuestionOption.objects.get(id=request.POST[str(question.id)])

        QuestionAttempt.objects.create(
                attempt=attempt,
                question=question,
                user_response=selected_option
                )

    template = get_template("quizzes/quiz_completion_confirmation.html")
    return HttpResponse(template.render({"quiz": quiz, "attempt": attempt}, request))

# This will show the results of the quiz
def quiz_results(request, id):
    attempt = get_object_or_404(QuizAttempt, id=id)

    template = get_template("quizzes/quiz_results.html")
    return HttpResponse(template.render({"attempt": attempt}, request))

quizzes/templates/quizzes/quiz_completion_confirmation.html
{% extends 'base.html' %} {% block content %}

<main style="max-width: 600px; margin: 0 auto;">
  <h1>Quiz Completed</h1>
  
  <p>Your response has been saved.</p>
  
  <p>
    Click <a href="{% url 'quizzes:quiz_results' attempt.id %}">here</a> to see
    your results
  </p>
</main>

{% endblock %}

quizzes/templates/quizzes/quiz_list.html
{% extends 'base.html' %} {% block content %}

<main style="max-width: 600px; margin: 0 auto;">
  <h1>Quizzes</h1>
  <ul>
    {% for quiz in object_list %}
    <li>
      {{ quiz.name }} (created {{ quiz.timestamp|date }})
      <a href="{% url 'quizzes:take_quiz' quiz.id %}">Take Quiz</a>
    </li>
    {% empty %}
    <li>No quizzes yet.</li>
    
    {% endfor %}
  </ul>
</main>

{% endblock %}

quizzes/templates/quizzes/quiz_results.html
{% extends 'base.html' %} {% block content %}

<main style="max-width: 600px; margin: 0 auto;">

  <h1>Quiz Results</h1>
  
  <p>Here are the results of your answers on the quiz: (<strong>{{ attempt.quiz.name }}</strong>) recorded {{ attempt.timestamp }}</p>
  
  <ul style="list-style-type: none;">
    {% for question in attempt.quiz.question_set.all %}
    
    <li style="padding-bottom: 10px;">
      <h2>{{ question.title }}</h2>
      
      <ul style="list-style-type: none;">
        {% for option in question.questionoption_set.all %}
        <li style="margin: 10px;">
          <input
          type="radio"
          id="{{ option.id }}"
          name="{{ question.id }}"
          value="{{ option.id }}"
          disabled="disabled"
          {% for answer in attempt.questionattempt_set.all %}
          {% if answer.question.id == question.id and answer.user_response == option %}
          checked="checked"
          {% else %}
          {% endif %}
          {% endfor %}
          />
          <label for="{{option.id}}">
            {% if option.correct %}
            <strong style="color: green;">
              {% endif %}
              
              {{ option.title }}
              
              {% for answer in attempt.questionattempt_set.all %}
              {% if answer.question.id == question.id and answer.user_response == option %}
              {% if answer.user_response.correct %}
              <strong style="color: green;">(correct)</strong>
              {% else %}
              <strong style="color: red;">(incorrect)</strong>
              {% endif %}
              {% endif %}
              {% endfor %}
              
              {% if option.correct %}
            </strong>
            {% endif %}
          </label>
        </li>
        
        {% endfor %}
      </ul>
    </li>
    {% endfor %}
  </ul>
  
  <p>
    Click <a href="{% url 'quizzes:take_quiz' attempt.quiz.id %}">here</a> to try
    again.
  </p>
  
</main>
{% endblock %}

quizzes/templates/quizzes/take_quiz.html
{% extends 'base.html' %} {% block content %}
<main style="max-width: 600px; margin: 0 auto;">

<h1>Quiz: {{ quiz.name }}</h1>
<form method="post" action="{% url 'quizzes:submit_quiz_attempt' quiz.id %}">
  {% csrf_token %}
  <ul style="list-style-type: none;">
    {% for question in quiz.question_set.all %}

    <li style="padding-bottom: 10px;">
      <h2>{{ question.title }}</h2>

      <ul style="list-style-type: none;">
        {% for option in question.questionoption_set.all %}
        <li style="margin: 10px;">
          <input
            type="radio"
            id="{{ option.id }}"
            name="{{question.id}}"
            value="{{ option.id }}"
            required
          />
          <label for="{{option.id}}">{{option.title}}</label>
        </li>

        {% endfor %}
      </ul>
    </li>
    {% endfor %}
  </ul>

  <button type="submit">Finish</button>
</form>

</main>
{% endblock %}