academy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), # /admin/
    path('', include('home.urls')), # /
    path('flashcards/', include('flashcard.urls')), # /flashcards/
    path('mathbubbles/', include('mathbubbles.urls')), # /mathbubbles/
    path('quizzes/', include('quizzes.urls')), # /quizzes/
    path('typer/', include('typer.urls')), # /typer/
]

flashcard/urls.py
from django.urls import path

from . import views

app_name = 'flashcards'

urlpatterns = [
    path("", views.flashcards_menu, name="flashcard-menu"),
    path("play/<str:id>", views.play_flashcards, name="play_flashcards"),
    path("add-deck", views.create_deck, name="create_deck"),
    path("add-flashcard", views.create_flashcard, name="create_flashcard"),
    path("add-subject", views.create_subject, name="create_subject"),
    path("delete-flashcard", views.delete_flashcard, name="delete_flashcard")
]

home/urls.py
from django.shortcuts import render
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home')
]

quizzes/urls.py
from django.urls import path

from . import views

app_name = 'quizzes'

urlpatterns = [
    # base route shows the list of quizzes
    path('', views.QuizListView.as_view(), name='quiz-list'),
    # route for taking a quiz
    path('quiz/<str:id>/take', views.take_quiz, name='take_quiz'),
    # route for submitting a quiz
    path('quiz/<str:id>/submit_attempt', views.submit_quiz_attempt, name='submit_quiz_attempt'),
    # route for showing the results of a quiz
    path('results/<str:id>', views.quiz_results, name='quiz_results'),
]

flashcard/models.py
from django.db import models
import uuid

# Create your models here.


class Subject(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,  # Generates unique id
                          editable=False)

    name = models.CharField(max_length=64, blank=False, null=False, default="")

    # created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    timestamp = models.DateTimeField(
        auto_now_add=True, db_index=True, editable=False)

    # change default plural name
    # class Meta:
    #     verbose_name_plural = "Quizzes"

    def __str__(self):
        return self.name


class Flashcard(models.Model):

    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,  # Generates unique id
                          editable=False)
    
    
    # models.do_nothing leaves the cards undeleted.
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    timestamp = models.DateTimeField(
        auto_now_add=True, db_index=True, editable=False)

    front_content = models.CharField(
        max_length=200, blank=False, null=False, default="")

    back_content = models.CharField(
        max_length=200, blank=False, null=False, default="")

    def __str__(self):
        return str(self.front_content)


class Deck(models.Model):

    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4,
                          editable=False)

    name = models.CharField(max_length=30, blank=False, null=False, default="")

    flashcards = models.ManyToManyField(Flashcard)

    def __str__(self):
        return str(self.name)

flashcard/forms.py
from django.forms import ModelForm
from django import forms
from .models import Deck, Flashcard, Subject
from django.db import models


class NewDeckForm(ModelForm):

    name = forms.TextInput()
    flashcards = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(), queryset=Flashcard.objects.all())

    class Meta():
        model = Deck
        fields = ["name", "flashcards"]


class AddCard(ModelForm):
    subject = forms.ModelChoiceField(
        widget=forms.Select(), queryset=Subject.objects.all())
    front_content = forms.TextInput()
    back_content = forms.TextInput()

    class Meta():
        model = Flashcard
        fields = ["subject", "front_content", "back_content"]


class AddSubject(ModelForm):
    name = forms.TextInput()

    class Meta():
        model = Subject
        fields = ["name"]


class DeleteFlashcard(ModelForm):

    front_content = forms.ModelChoiceField(
        widget=forms.Select(), queryset=Flashcard.objects.all())

    class Meta():
        model = Flashcard
        fields = ["front_content"]

flashcard/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from django.utils import timezone
from django.views.generic.list import ListView
from flashcard.forms import NewDeckForm, AddCard, AddSubject, DeleteFlashcard
from .models import Flashcard, Deck, Subject

class FlashcardListView(ListView):

    model = Flashcard


def flashcards_menu(request):

    decks = Deck.objects.all()

    template = get_template("flashcard/flashcards_menu.html")
    return HttpResponse(template.render({"decks": decks}, request))


def play_flashcards(request, id):  # Also add subject as second argument
    #Deck = get_object_or_404(Deck, id=id)
    # Deck.objects.all()
    deck = get_object_or_404(Deck, id=id)
    flashcards = deck.flashcards.all()

    template = get_template("flashcard/flashcard_game.html")
    return HttpResponse(template.render({"deck": deck, "flashcards": flashcards}, request))


def create_deck(request):

    form = NewDeckForm(request.POST)
    if form.is_valid():
        form.save()
        form = NewDeckForm()

    template = get_template("flashcard/render_form.html")
    return HttpResponse(template.render({"form": form, "value": "Save"}, request))


def create_flashcard(request):

    form = AddCard(request.POST)
    if form.is_valid():
        form.save()
        form = AddCard()

    template = get_template("flashcard/render_form.html")
    return HttpResponse(template.render({"form": form, "value": "Save"}, request))


def create_subject(request):

    form = AddSubject(request.POST)
    if form.is_valid():
        form.save()
        form = AddSubject()

    template = get_template("flashcard/render_form.html")
    return HttpResponse(template.render({"form": form, "value": "Save"}, request))


def delete_flashcard(request):
    

    form = DeleteFlashcard(request.POST)
    if form.is_valid():
        field = form.cleaned_data["front_content"]
        flashcard = Flashcard.objects.get(front_content=field)
        flashcard.delete()        

    template = get_template("flashcard/render_form.html")
    return HttpResponse(template.render({"form": form, "value": "Delete"}, request))

flashcard/templates/flashcard/flashcard_game.html
{% extends 'base.html' %} 

{% block content %}

{% comment %} {% load static %} 
<link rel="stylesheet" href="{% static 'flashcard_app.js' %}"> {% endcomment %}
<style>
    :root {
        --primary: #FFCE00;
        --secondary: #FE4880;
        --dark: #212121;
        --light: #F3F3F3;
      }
      
      * {
        margin: 0;
        padding: 0;
      }
      
      body {
        font-family: montserrat, sans-serif;
        width: 100%;
        min-height: 100vh;
      }
      
      .card {
        margin: 100px auto 0;
        width: 400px;
        height: 600px;
        perspective: 1000px;
      }
      
      .card__inner {
        width: 100%;
        height: 100%;
        transition: transform 1s;
        transform-style: preserve-3d;
        cursor: pointer;
        position: relative;
      }
      
      .card__inner.is-flipped {
        transform: rotateY(180deg);
      }
      
      
      .card__face {
        position: absolute;
        width: 100%;
        height: 100%;
        -webkit-backface-visibility: hidden;
        backface-visibility: hidden;
        overflow: hidden;
        border-radius: 16px;
        box-shadow: 0px 3px 18px 3px rgba(0, 0, 0, 0.2);
      }
      
      .card__face--front {
        background-image: linear-gradient(to bottom right, var(--primary), var(--secondary));
        display: flex;
        align-items: center;
        justify-content: center;
      }
      
      .card__face--front h2 {
        color: #FFF;
        font-size: 32px;
      }
      
      .card__face--back {
        background-color: var(--light);
        transform: rotateY(180deg);
      }
      
      .card__content {
        width: 100%;
        height: 100%;
      }
      
      .card__header {
        position: relative;
        padding: 30px 30px 40px;
      }
      
      .card__header:after {
        content: '';
        display: block;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-image: linear-gradient(to bottom left, var(--primary) 10%, var(--secondary) 115%);
        z-index: -1;
        border-radius: 0px 0px 50% 0px;
      }
      
      .pp {
        display: block;
        width: 128px;
        height: 128px;
        margin: 0 auto 30px;
        border-radius: 50%;
        background-color: #FFF;
        border: 5px solid #FFF;
        object-fit: cover;
      }
      
      .card__header h2 {
        color: #FFF;
        font-size: 32px;
        font-weight: 900;
        text-transform: uppercase;
        text-align: center;
      }
      
      .card__body {
        padding: 30px;
      }
      
      .card__body h3 {
        color: var(--dark);
        font-size: 24px;
        font-weight: 600;
        margin-bottom: 15px;
      }
      
      .card__body p {
        color: var(--dark);
        font-size: 18px;
        line-height: 1.4;
      }

</style> 
<h1>{{ deck.name }}</h1>
<ul>
  {% for flashcard in flashcards %}
  <li>
    <div class="card">
		<div class="card__inner">
			<div class="card__face card__face--front">
				{{ flashcard.front_content }}
			</div>
			<div class="card__face card__face--back">
				<div class="card__content">
					<div class="card__body">
						{{ flashcard.back_content }}
					</div>
				</div>
			</div>
		</div>
	</div>
  </li>

  {% endfor %}
</ul>
<script>
    
    var cards = document.querySelectorAll(".card__inner");
    
    cards.forEach((card)=>{
        card.addEventListener("click", function (e) {
            card.classList.toggle('is-flipped');
            });
    })
</script>
{% endblock %}

flashcard/templates/flashcard/flashcard_list.html
{% extends 'base.html' %} {% block content %}

<h1>Flashcards</h1>
<ul>
  {% for flashcard in object_list %}
  <li>
    {{ flashcard.subject }} {% comment %}
    <a href="{% url 'quizzes:take_quiz' quiz.id %}">Take Quiz</a>
    {% endcomment %}
  </li>
  {% empty %}
  <li>No flashcards yet.</li>
  {% endfor %}
</ul>

{% endblock %}

flashcard/templates/flashcard/flashcards_menu.html
{% extends 'base.html' %} 
{% block content %}
<section>
    <h2>Choose a deck and start practicing!</h2>
    <ul>
        {% for deck in decks %}
        <li><a href={% url 'flashcards:play_flashcards' deck.id %}>{{ deck.name }}</a></li>
        {% endfor %}
    </ul>
</section>
<section>
    <a href={% url 'flashcards:create_deck' %}>Create a new deck</a>
</section>
<section>
    <h2>Flashcards</h2>
    <ul>
        <li><a href={% url 'flashcards:create_flashcard'%}>Add new cards</a></li>
        <li><a href={% url 'flashcards:delete_flashcard' %}>Delete cards</a></li>
        <li><a href={% url 'flashcards:create_subject' %}>Add a new subject</a></li>
    </ul>
</section>
{% endblock %}

flashcard/templates/flashcard/render_form.html
{% extends 'base.html' %} 

{% block content %}
<form method="POST"> {% csrf_token %}
{{form.as_p}}
<input type="submit" value={{value}}/>
</form>
{% endblock %}